// Copyright 2026 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter-convert-font-image` with arguments:
//    format         | mono16
//    unicode_glyphs | 0123456789
//    output         | qp_font
//    input          | font_huge.png

#pragma once

#include <qp.h>

extern const uint32_t font_font_huge_length;
extern const uint8_t  font_font_huge[10884];
