[package]
name = "keyboard"
version = "0.1.0"
edition = "2024"

[lib]
name = "keyboard"
path = "src/lib.rs"
crate-type = ["rlib", "staticlib"]

[dependencies]
embedded-alloc = "0.6.0"
panic-halt = "1.0.0"
once_cell = { version = "1.21.1", default-features = false, features = [
    "alloc",
    "critical-section",
    "atomic-polyfill",
] }
micromath = "2.1.0"
anyhow = { version = "1.0.97", default-features = false }
qmk-sys = { path = "../qmk_sys" }
serde = { version = "1.0.228", default-features = false, features = ["alloc", "derive"] }
postcard = { version = "1.1.3", features = ["alloc"] }
hid-bridge = { path = "../../../shared/hid-bridge", default-features = false, features = ["no_std"] }
spin = { version = "0.10.0", features = ["rwlock", "portable-atomic"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rp2040-panic-usb-boot = "0.6.0"
rp2040-hal = { version = "0.11.0", features = ["critical-section-impl"] }
critical-section = "1.2.0"

[target.thumbv6m-none-eabi.dependencies]
portable-atomic = { version = "1.8", features = ["unsafe-assume-single-core"] }
